<?php

namespace CastingBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{

    public function gettoutlesparticipation()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT c.nomCasting  as nom,c.id as cid , u.id as id  , p.id as pid  ,p.resultatCasting as resultat  from CastingBundle:Participation p JOIN  CastingBundle:Casting c WITH p.casting=c.id  JOIN AppBundle:User u WITH p.user=u.id");
        return $query->getResult();

    }

}
