<?php

namespace EventsBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{


    public function getmesreservation()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT e.nameEvent as nom, r.id as rid ,r.datereservation as date , r.nbplaceReserv as nbr ,r.etat as etat , u.id as id  from EventsBundle:Reservation r JOIN EventsBundle:Events e WITH r.event=e.id  JOIN EventsBundle:User u WITH r.user=u.id");
        return $query->getResult();

    }

    public function gettoutlesreservation()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT e.nameEvent as nom, r.id as rid ,r.datereservation as date , r.nbplaceReserv as nbr ,r.etat as etat , u.id as id , u.username as username  from EventsBundle:Reservation r JOIN EventsBundle:Events e WITH r.event=e.id  JOIN EventsBundle:User u WITH r.user=u.id");
        return $query->getResult();

    }
}
