<?php

namespace CastingBundle\Repository;

/**
 * NotificationrParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationrParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
